/*
 * Org.liu Inc.
 *middlegen.plugins.iwallet.IWalletPlugin@689604d9
 *com.wind.bux.common.dal.Money
 * Copyright (c) 2014 All Rights Reserved.
 */
package com.pdstars.dal.dataobject;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;



/**
 * Base class for all data objects.
 *
 * This file is generated by <tt>pjgl-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>pjgl</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may be
 * OVERWRITTEN by someone else. To modify the file, you should go to directory
 * <tt>(project-home)/trunk/XX-dalgen</tt>, and find the corresponding
 * configuration file. Modify the configuration file according to your needs,
 * then run <tt>pjgl-dalgen</tt> to generate this file.
 *
 * @author Frank.Fan
 */
@SuppressWarnings("serial")
public class BaseDO implements Serializable {

  /**
   * @return
   *
   * @see java.lang.Object#toString()
   */
  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
  }
}
