package com.pdstars.dal.dataobject;

import java.util.Date;

public class Detail extends BaseDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.type_id
     *
     * @mbg.generated
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detail.insert_time
     *
     * @mbg.generated
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.id
     *
     * @return the value of detail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.id
     *
     * @param id the value for detail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.type_id
     *
     * @return the value of detail.type_id
     *
     * @mbg.generated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.type_id
     *
     * @param typeId the value for detail.type_id
     *
     * @mbg.generated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.count
     *
     * @return the value of detail.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.count
     *
     * @param count the value for detail.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detail.insert_time
     *
     * @return the value of detail.insert_time
     *
     * @mbg.generated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detail.insert_time
     *
     * @param insertTime the value for detail.insert_time
     *
     * @mbg.generated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}