package com.pdstars.dal.daointerface;

import com.pdstars.dal.dataobject.Detail;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DetailMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table detail
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table detail
	 *
	 * @mbg.generated
	 */
	int insert(Detail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table detail
	 *
	 * @mbg.generated
	 */
	Detail selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table detail
	 *
	 * @mbg.generated
	 */
	List<Detail> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table detail
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Detail record);

	/**
	 * 根据typeId获取详情信息
	 * @author:Yanfa-0509
	 * @date:Oct 24, 2019 10:33:21 AM
	 * @param typeId
	 * @return
	 */
	List<Detail> selectByTypeId(@Param("typeId") Long typeId);
	
	/**
	 * 获取前N条数据
	 * @author:Yanfa-0509
	 * @date:Oct 24, 2019 10:50:02 AM
	 * @param n
	 * @return
	 */
	List<Detail> selectTopN(@Param("n") Integer n);
}