package com.pdstars.dal.daointerface;

import com.pdstars.dal.dataobject.Type;
import com.pdstars.dal.dataobject.TypeStatistics;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated
     */
    int insert(Type record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated
     */
    Type selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated
     */
    List<Type> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Type record);
    
    /**
     * 根据typeName模糊匹配记录
     * @author:Yanfa-0509
     * @date:Oct 24, 2019 10:23:17 AM
     * @param typeName
     * @return
     */
    List<Type> selectByTypeName(@Param("typeName") String typeName);
    
    /**
     * 获取type统计
     * @author:Yanfa-0509
     * @date:Oct 24, 2019 5:32:23 PM
     * @return
     */
    List<TypeStatistics> selectGroupBy();
}